# Generated by Django 5.1.3 on 2024-11-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename__id_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_on_hand',
            field=models.IntegerField(default=100),
        ),
    ]
