# Generated by Django 5.1.3 on 2024-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customerinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
