# Generated by Django 5.1.3 on 2024-11-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customerinformation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='handling_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
