# Generated by Django 5.1.3 on 2024-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customerinformation_handling_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='credit_card_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
